### ISSUE TITLE
Wiring ESP32 with ILI9488 FT6236 and SHT35

### ISSUE THREAD

**Issue by LawDeveloper** [DustinWatts/FT6236#7]
Hi! Thanks a lot for this file driver!

Could you please help me with a question about two left wires?

I m using a ESP which is connected to a ILI9488(SPI) with a FT6236 and a SHT35(I2C).

On the display there are still two pins left not connected for the touch. The are labeled with CTP-INT and CTP-RST. 

Do I need to connect them? I cant find anything about those to pins in your code. 

Everything works great but I am concerned if everything is the way it should be or if there might be a problem because of those two missing wires and another device (SHT35) connected over I2C.

Would you mind helping me out with this?

Thanks a lot!

**Comment by DustinWatts** [comment]
Hi @LawDeveloper You are fine like this. The reset pin is not needed. And the interrupt pin only if you want to know when there is a touch instead of checking in the code. You can connect that pin to any GPIO as an input and for example setup an interrupt routine. Or you could use that pin to wake up from sleep like I did on the FreeTouchDeck.

If you are happy with this answer you can close the issue :)

**Comment by LawDeveloper** [comment]
Hi @DustinWatts!

Thank you for your prompt and very helpful reply!
